<a href="https://colab.research.google.com/github/massinoLight/AIEMeubleFinale/blob/master/classification_tickets_MLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import tensorflow as tf
import pandas as pd
from sklearn.model_selection import train_test_split
from tensorflow import keras
from tensorflow.keras import layers

In [3]:
LUPClosed= pd.read_csv('/content/sample_data/jeux_de_donnes_sans_vecteur.csv',index_col=0)

In [4]:
feature_cols = ['lbs_projet','lb_code_archi','lb_pilot_so_nom_prenom','lb_pilot_dept','lbs_direction_gf','lbs_criticite_qu']
X = LUPClosed[feature_cols].to_numpy() # Features
y = LUPClosed['class'].to_numpy() # Target variable

In [10]:
LUPClosed= pd.read_csv('/content/sample_data/jeux_de_donnees.csv',index_col=0)

In [11]:
target=['class']
feature_cols =LUPClosed.columns
z = [item for item in feature_cols if item not in target]

X = LUPClosed[z] # Features
y = LUPClosed['class'] # Target variabletarget=['class']
feature_cols =LUPClosed.columns
z = [item for item in feature_cols if item not in target]

X = LUPClosed[z].to_numpy() # Features
y = LUPClosed['class'].to_numpy() # Target variable

In [5]:
optimizers=['sgd', 'adam', 'rmsprop'] # Tu peux essayer adam ou rmsprop, sgd est le plus basique mais marche bien avec les problèmes simples

In [26]:
nb_features

306

In [29]:
X

array([[ 3.40000000e+01,  0.00000000e+00,  4.94000000e+02, ...,
         6.44749254e-01,  8.06782049e-01, -1.97688771e+00],
       [ 3.40000000e+01,  0.00000000e+00,  4.94000000e+02, ...,
         1.31420101e+00,  7.28355930e-01, -1.33550523e+00],
       [ 3.40000000e+01,  0.00000000e+00,  4.94000000e+02, ...,
         1.31420101e+00,  7.28355930e-01, -1.33550523e+00],
       ...,
       [ 2.20000000e+01,  5.00000000e+00,  3.37000000e+02, ...,
        -2.27166910e+00,  4.20113257e-01, -7.50924669e-01],
       [ 1.00000000e+00,  0.00000000e+00,  1.74000000e+02, ...,
         3.44273475e-01, -5.73832157e-02,  1.57681724e+00],
       [ 2.90000000e+01,  6.00000000e+00,  2.78000000e+02, ...,
         1.53120350e+00,  2.66864225e-01, -1.26474003e+00]])

In [30]:
y

array([1, 1, 1, ..., 2, 1, 3])

In [31]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

In [32]:
x_val = X_train[-1000:]
y_val = y_train[-1000:]

In [33]:
# Avec tf.one_hot, tu vas les transformer en vecteurs
one_hot_labels = tf.one_hot(y_train,4)
one_hot_labels

<tf.Tensor: shape=(3703, 4), dtype=float32, numpy=
array([[0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       ...,
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [34]:
one_hot_labels_val = tf.one_hot(y_val,4)
one_hot_labels_val

<tf.Tensor: shape=(1000, 4), dtype=float32, numpy=
array([[0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       ...,
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [39]:
num_classes = 4

model = tf.keras.Sequential([
    layers.Dense(128,activation='relu'),
    layers.Dense(64,activation='relu'),
    layers.Dense(32,activation='relu'),
    layers.Dense(16,activation='relu'),
    layers.Dense(num_classes, activation='softmax')
])
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [40]:
history = model.fit(
    X_train,
    one_hot_labels,
    batch_size=10,
    epochs=100,
    validation_data=(x_val, one_hot_labels_val),
    callbacks=tf.keras.callbacks.EarlyStopping(monitor='loss', patience=3,min_delta=0)
)


Epoch 1/100
371/371 [==============================] - 2s 3ms/step - loss: 1.2563 - acc: 0.4750 - val_loss: 1.0248 - val_acc: 0.5730
Epoch 2/100
371/371 [==============================] - 1s 3ms/step - loss: 0.9187 - acc: 0.6338 - val_loss: 0.9107 - val_acc: 0.6200
Epoch 3/100
371/371 [==============================] - 1s 3ms/step - loss: 0.7506 - acc: 0.7146 - val_loss: 0.6338 - val_acc: 0.7530
Epoch 4/100
371/371 [==============================] - 1s 4ms/step - loss: 0.5984 - acc: 0.7742 - val_loss: 0.5071 - val_acc: 0.8070
Epoch 5/100
371/371 [==============================] - 1s 4ms/step - loss: 0.4912 - acc: 0.8110 - val_loss: 0.3833 - val_acc: 0.8720
Epoch 6/100
371/371 [==============================] - 1s 2ms/step - loss: 0.4084 - acc: 0.8517 - val_loss: 0.3163 - val_acc: 0.8820
Epoch 7/100
371/371 [==============================] - 1s 2ms/step - loss: 0.3276 - acc: 0.8841 - val_loss: 0.4246 - val_acc: 0.8510
Epoch 8/100
371/371 [==============================] - 1s 4ms/step - 

In [41]:
model.summary()

Model: "sequential_12"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_36 (Dense)            (None, 128)               39296     
                                                                 
 dense_37 (Dense)            (None, 64)                8256      
                                                                 
 dense_38 (Dense)            (None, 32)                2080      
                                                                 
 dense_39 (Dense)            (None, 16)                528       
                                                                 
 dense_40 (Dense)            (None, 4)                 68        
                                                                 
Total params: 50,228
Trainable params: 50,228
Non-trainable params: 0
_________________________________________________________________
